#!/bin/bash
cd $1
echo "stopping qoorate"
pid_file=`cat ./profiles/qoorate/pid_file`
echo "looking for pid file: $pid_file"
if [ -f "$pid_file" ]
    then
        pid=`cat $pid_file`
        kill  $pid
        rm -f $pid_file
        echo "Stopped qoorate"
    else
        echo "no pid file found"
fi

echo "stopping uploader"
pid_file=`cat ./profiles/uploader/pid_file`
echo "looking for pid file: $pid_file"
if [ -f "$pid_file" ]
    then
        pid=`cat $pid_file`
        kill  $pid
        rm -f $pid_file
        echo "Stopped uploader"
    else
        echo "no pid file found"
fi

echo "done reloading"
